### ISSUE TITLE
Quick fix here please

### ISSUE THREAD

**Issue by roblav96** [TabDigital/restify-cors-middleware#9]
I'm getting this error while installing this.

`Robs-MacBook-Pro:hot-reports-server roblav96$ npm i restify-cors-middleware
npm WARN peerDependencies The peer dependency restify@2.6.x - 3.0.x included from restify-cors-middleware will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "restify-cors-middleware"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package restify@4.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer restify-cors-middleware@0.0.5 wants restify@2.6.x - 3.0.x`

Looks like an easy fix. Everything works fine, just annoying to see in my console. Thanks! :D

**Comment by rprieto** [comment]
Hi, I think this is working as expected. `restify-cors-middleware` has a peer dependency on `restify@2.6.x-3.0.x` (versions we tested with). I believe the warning means
- in **npm 2**, if a suitable `restify` isn't available at the top level, it will install a valid one as a dependency of `restify-cors-middleware` (and things will work OK)
- in **npm 3**, if a suitable `restify` isn't available at the top level, it won't install it because *peer dependency* now means "I expect this to be present". Things might not work anymore.

The warning you're getting is because you're running `restify@4.0.0`, which is not compatible, and it might not work anymore in **npm 3**. I'd suggest checking if  restify 4 is compatible so we can udpate the dependency. The easiest way to do that is to delete `./node_modules/restify-cors-middleware/node_modules/restify` (the local install) so it picks up your version instead.

**Comment by roblav96** [comment]
Ahhh gotcha! That makes sense now. I'll give it a shot right now. Thank man!

**Comment by roblav96** [comment]
The dependencies need to be changed to reflect restify 4.X by the way
